/**
 * scripts/reference/table-special.mjs
 * Особые случаи: status, former_names, capitals.
 */

export const STATUS_OVERRIDES = {
  TWN: { status: 'disputed', note: 'UN M49: province of China. ISO 3166-1 assigned.' },
  XKX: { status: 'disputed', valid_from: '2008-02-17', note: 'Not ISO 3166-1 official. User-assigned code.' },
  PSE: { status: 'observer', note: 'UN observer state since 2012.' },
  VAT: { status: 'observer', note: 'UN observer state.' },
  HKG: { status: 'territory', parent_country: 'CHN', valid_from: '1997-07-01', note: 'Special Administrative Region of China.' },
  MAC: { status: 'territory', parent_country: 'CHN', valid_from: '1999-12-20', note: 'Special Administrative Region of China.' },
  GRL: { status: 'territory', parent_country: 'DNK', note: 'Autonomous territory of Denmark.' },
  FRO: { status: 'territory', parent_country: 'DNK', note: 'Autonomous territory of Denmark.' },
  PRI: { status: 'territory', parent_country: 'USA', note: 'Unincorporated territory of USA.' },
  GUM: { status: 'territory', parent_country: 'USA' },
  VIR: { status: 'territory', parent_country: 'USA' },
  ASM: { status: 'territory', parent_country: 'USA' },
  MNP: { status: 'territory', parent_country: 'USA' },
  UMI: { status: 'territory', parent_country: 'USA' },
  GIB: { status: 'territory', parent_country: 'GBR' },
  BMU: { status: 'territory', parent_country: 'GBR' },
  CYM: { status: 'territory', parent_country: 'GBR' },
  FLK: { status: 'territory', parent_country: 'GBR' },
  SGS: { status: 'territory', parent_country: 'GBR' },
  IOT: { status: 'territory', parent_country: 'GBR' },
  VGB: { status: 'territory', parent_country: 'GBR' },
  TCA: { status: 'territory', parent_country: 'GBR' },
  MSR: { status: 'territory', parent_country: 'GBR' },
  SHN: { status: 'territory', parent_country: 'GBR' },
  PCN: { status: 'territory', parent_country: 'GBR' },
  AIA: { status: 'territory', parent_country: 'GBR' },
  GGY: { status: 'territory', parent_country: 'GBR' },
  JEY: { status: 'territory', parent_country: 'GBR' },
  IMN: { status: 'territory', parent_country: 'GBR' },
  GLP: { status: 'territory', parent_country: 'FRA' },
  MTQ: { status: 'territory', parent_country: 'FRA' },
  GUF: { status: 'territory', parent_country: 'FRA' },
  REU: { status: 'territory', parent_country: 'FRA' },
  MYT: { status: 'territory', parent_country: 'FRA' },
  BLM: { status: 'territory', parent_country: 'FRA' },
  MAF: { status: 'territory', parent_country: 'FRA' },
  SPM: { status: 'territory', parent_country: 'FRA' },
  WLF: { status: 'territory', parent_country: 'FRA' },
  PYF: { status: 'territory', parent_country: 'FRA' },
  NCL: { status: 'territory', parent_country: 'FRA' },
  ATF: { status: 'territory', parent_country: 'FRA' },
  ABW: { status: 'territory', parent_country: 'NLD' },
  CUW: { status: 'territory', parent_country: 'NLD' },
  SXM: { status: 'territory', parent_country: 'NLD' },
  BES: { status: 'territory', parent_country: 'NLD' },
  ALA: { status: 'territory', parent_country: 'FIN' },
  SJM: { status: 'territory', parent_country: 'NOR' },
  BVT: { status: 'territory', parent_country: 'NOR' },
  CXR: { status: 'territory', parent_country: 'AUS' },
  CCK: { status: 'territory', parent_country: 'AUS' },
  HMD: { status: 'territory', parent_country: 'AUS' },
  NFK: { status: 'territory', parent_country: 'AUS' },
  COK: { status: 'territory', parent_country: 'NZL' },
  NIU: { status: 'territory', parent_country: 'NZL' },
  TKL: { status: 'territory', parent_country: 'NZL' },
  ESH: { status: 'disputed', note: 'Disputed territory (Western Sahara).' },
  ATA: { status: 'reserved', note: 'Not a country. Reserved for Antarctica.' }
};

export const FORMER_NAMES = {
  MMR: [{ name: 'Burma', valid_until: '1989-06-18' }],
  LKA: [{ name: 'Ceylon', valid_until: '1972-05-22' }],
  IRN: [{ name: 'Persia', valid_until: '1935-03-21' }],
  THA: [{ name: 'Siam', valid_until: '1939-06-23' }],
  COD: [{ name: 'Zaire', valid_until: '1997-05-17' }],
  ZWE: [{ name: 'Rhodesia', valid_until: '1980-04-18' }, { name: 'Southern Rhodesia', valid_until: '1980-04-18' }],
  BFA: [{ name: 'Upper Volta', valid_until: '1984-08-04' }],
  BEN: [{ name: 'Dahomey', valid_until: '1975-11-30' }],
  NAM: [{ name: 'South West Africa', valid_until: '1990-03-21' }],
  KHM: [{ name: 'Kampuchea', valid_until: '1989-05-01' }],
  CZE: [{ name: 'Czech Republic', valid_until: '2016-07-05' }],
  MKD: [{ name: 'Macedonia', valid_until: '2019-02-12' }, { name: 'Yugoslav Republic of Macedonia', valid_until: '2019-02-12' }],
  SWZ: [{ name: 'Swaziland', valid_until: '2018-04-19' }],
  RUS: [{ name: 'Russian Soviet Federative Socialist Republic', valid_until: '1991-12-25' }, { name: 'Soviet Union', valid_until: '1991-12-26' }, { name: 'USSR', valid_until: '1991-12-26' }],
  TUR: [{ name: 'Turkey', valid_until: null, note: 'Renamed to Turkiye in 2022; both accepted.' }],
  NLD: [{ name: 'Holland', valid_until: null, note: 'Informal name.' }],
  CIV: [{ name: 'Ivory Coast', valid_until: null, note: 'English name; official since 1986 is Cote d Ivoire.' }]
};

export const CAPITALS = {
  RUS: { name_en: 'Moscow', name_ru: 'Москва', name_local: 'Москва', lat: 55.7558, lon: 37.6173 },
  USA: { name_en: 'Washington, D.C.', name_ru: 'Вашингтон', name_local: 'Washington, D.C.', lat: 38.9072, lon: -77.0369 },
  CHN: { name_en: 'Beijing', name_ru: 'Пекин', name_local: '北京', lat: 39.9042, lon: 116.4074 },
  GBR: { name_en: 'London', name_ru: 'Лондон', name_local: 'London', lat: 51.5074, lon: -0.1278 },
  FRA: { name_en: 'Paris', name_ru: 'Париж', name_local: 'Paris', lat: 48.8566, lon: 2.3522 },
  DEU: { name_en: 'Berlin', name_ru: 'Берлин', name_local: 'Berlin', lat: 52.5200, lon: 13.4050 },
  ITA: { name_en: 'Rome', name_ru: 'Рим', name_local: 'Roma', lat: 41.9028, lon: 12.4964 },
  JPN: { name_en: 'Tokyo', name_ru: 'Токио', name_local: '東京', lat: 35.6762, lon: 139.6503 },
  IND: { name_en: 'New Delhi', name_ru: 'Нью-Дели', name_local: 'नई दिल्ली', lat: 28.6139, lon: 77.2090 },
  BRA: { name_en: 'Brasilia', name_ru: 'Бразилиа', name_local: 'Brasilia', lat: -15.7939, lon: -47.8828 },
  CAN: { name_en: 'Ottawa', name_ru: 'Оттава', name_local: 'Ottawa', lat: 45.4215, lon: -75.6972 },
  AUS: { name_en: 'Canberra', name_ru: 'Канберра', name_local: 'Canberra', lat: -35.2809, lon: 149.1300 },
  UKR: { name_en: 'Kyiv', name_ru: 'Киев', name_local: 'Київ', lat: 50.4501, lon: 30.5234 },
  TUR: { name_en: 'Ankara', name_ru: 'Анкара', name_local: 'Ankara', lat: 39.9334, lon: 32.8597 },
  ISR: { name_en: 'Jerusalem', name_ru: 'Иерусалим', name_local: 'ירושלים', lat: 31.7683, lon: 35.2137 },
  IRN: { name_en: 'Tehran', name_ru: 'Тегеран', name_local: 'تهران', lat: 35.6892, lon: 51.3890 },
  SAU: { name_en: 'Riyadh', name_ru: 'Эр-Рияд', name_local: 'الرياض', lat: 24.7136, lon: 46.6753 },
  EGY: { name_en: 'Cairo', name_ru: 'Каир', name_local: 'القاهرة', lat: 30.0444, lon: 31.2357 },
  ZAF: { name_en: 'Pretoria', name_ru: 'Претория', name_local: 'Pretoria', lat: -25.7479, lon: 28.2293 },
  KOR: { name_en: 'Seoul', name_ru: 'Сеул', name_local: '서울', lat: 37.5665, lon: 126.9780 },
  PRK: { name_en: 'Pyongyang', name_ru: 'Пхеньян', name_local: '평양', lat: 39.0392, lon: 125.7625 },
  MEX: { name_en: 'Mexico City', name_ru: 'Мехико', name_local: 'Ciudad de Mexico', lat: 19.4326, lon: -99.1332 },
  ARG: { name_en: 'Buenos Aires', name_ru: 'Буэнос-Айрес', name_local: 'Buenos Aires', lat: -34.6037, lon: -58.3816 },
  POL: { name_en: 'Warsaw', name_ru: 'Варшава', name_local: 'Warszawa', lat: 52.2297, lon: 21.0122 },
  SWE: { name_en: 'Stockholm', name_ru: 'Стокгольм', name_local: 'Stockholm', lat: 59.3293, lon: 18.0686 },
  NOR: { name_en: 'Oslo', name_ru: 'Осло', name_local: 'Oslo', lat: 59.9139, lon: 10.7522 },
  FIN: { name_en: 'Helsinki', name_ru: 'Хельсинки', name_local: 'Helsinki', lat: 60.1699, lon: 24.9384 },
  DNK: { name_en: 'Copenhagen', name_ru: 'Копенгаген', name_local: 'Kobenhavn', lat: 55.6761, lon: 12.5683 },
  NLD: { name_en: 'Amsterdam', name_ru: 'Амстердам', name_local: 'Amsterdam', lat: 52.3676, lon: 4.9041 },
  BEL: { name_en: 'Brussels', name_ru: 'Брюссель', name_local: 'Brussel', lat: 50.8503, lon: 4.3517 },
  CHE: { name_en: 'Bern', name_ru: 'Берн', name_local: 'Bern', lat: 46.9480, lon: 7.4474 },
  AUT: { name_en: 'Vienna', name_ru: 'Вена', name_local: 'Wien', lat: 48.2082, lon: 16.3738 },
  GRC: { name_en: 'Athens', name_ru: 'Афины', name_local: 'Αθηνα', lat: 37.9838, lon: 23.7275 },
  ESP: { name_en: 'Madrid', name_ru: 'Мадрид', name_local: 'Madrid', lat: 40.4168, lon: -3.7038 },
  PRT: { name_en: 'Lisbon', name_ru: 'Лиссабон', name_local: 'Lisboa', lat: 38.7223, lon: -9.1393 },
  IRL: { name_en: 'Dublin', name_ru: 'Дублин', name_local: 'Dublin', lat: 53.3498, lon: -6.2603 },
  CZE: { name_en: 'Prague', name_ru: 'Прага', name_local: 'Praha', lat: 50.0755, lon: 14.4378 },
  HUN: { name_en: 'Budapest', name_ru: 'Будапешт', name_local: 'Budapest', lat: 47.4979, lon: 19.0402 },
  ROU: { name_en: 'Bucharest', name_ru: 'Бухарест', name_local: 'Bucuresti', lat: 44.4268, lon: 26.1025 },
  BGR: { name_en: 'Sofia', name_ru: 'София', name_local: 'София', lat: 42.6977, lon: 23.3219 },
  SRB: { name_en: 'Belgrade', name_ru: 'Белград', name_local: 'Beograd', lat: 44.7866, lon: 20.4489 },
  HRV: { name_en: 'Zagreb', name_ru: 'Загреб', name_local: 'Zagreb', lat: 45.8150, lon: 15.9819 },
  SVN: { name_en: 'Ljubljana', name_ru: 'Любляна', name_local: 'Ljubljana', lat: 46.0569, lon: 14.5058 },
  SVK: { name_en: 'Bratislava', name_ru: 'Братислава', name_local: 'Bratislava', lat: 48.1486, lon: 17.1077 },
  LTU: { name_en: 'Vilnius', name_ru: 'Вильнюс', name_local: 'Vilnius', lat: 54.6872, lon: 25.2797 },
  LVA: { name_en: 'Riga', name_ru: 'Рига', name_local: 'Riga', lat: 56.9496, lon: 24.1052 },
  EST: { name_en: 'Tallinn', name_ru: 'Таллин', name_local: 'Tallinn', lat: 59.4370, lon: 24.7536 },
  BLR: { name_en: 'Minsk', name_ru: 'Минск', name_local: 'Минск', lat: 53.9006, lon: 27.5590 },
  MDA: { name_en: 'Chisinau', name_ru: 'Кишинёв', name_local: 'Chisinau', lat: 47.0105, lon: 28.8638 },
  GEO: { name_en: 'Tbilisi', name_ru: 'Тбилиси', name_local: 'თბილისი', lat: 41.7151, lon: 44.8271 },
  ARM: { name_en: 'Yerevan', name_ru: 'Ереван', name_local: 'Երևան', lat: 40.1792, lon: 44.4991 },
  AZE: { name_en: 'Baku', name_ru: 'Баку', name_local: 'Baki', lat: 40.4093, lon: 49.8671 },
  KAZ: { name_en: 'Astana', name_ru: 'Астана', name_local: 'Astana', lat: 51.1694, lon: 71.4491 },
  UZB: { name_en: 'Tashkent', name_ru: 'Ташкент', name_local: 'Toshkent', lat: 41.2995, lon: 69.2401 },
  KGZ: { name_en: 'Bishkek', name_ru: 'Бишкек', name_local: 'Бишкек', lat: 42.8746, lon: 74.5698 },
  TJK: { name_en: 'Dushanbe', name_ru: 'Душанбе', name_local: 'Душанбе', lat: 38.5598, lon: 68.7870 },
  TKM: { name_en: 'Ashgabat', name_ru: 'Ашхабад', name_local: 'Asgabat', lat: 37.9601, lon: 58.3261 },
  MNG: { name_en: 'Ulaanbaatar', name_ru: 'Улан-Батор', name_local: 'Улаанбаатар', lat: 47.8864, lon: 106.9057 },
  THA: { name_en: 'Bangkok', name_ru: 'Бангкок', name_local: 'กรุงเทพ', lat: 13.7563, lon: 100.5018 },
  VNM: { name_en: 'Hanoi', name_ru: 'Ханой', name_local: 'Ha Noi', lat: 21.0285, lon: 105.8542 },
  KHM: { name_en: 'Phnom Penh', name_ru: 'Пномпень', name_local: 'ភ្នំពេញ', lat: 11.5564, lon: 104.9282 },
  LAO: { name_en: 'Vientiane', name_ru: 'Вьентьян', name_local: 'ວຽງຈັນ', lat: 17.9757, lon: 102.6331 },
  MMR: { name_en: 'Naypyidaw', name_ru: 'Нейпьидо', name_local: 'နေပြည်တော်', lat: 19.7633, lon: 96.0785 },
  IDN: { name_en: 'Jakarta', name_ru: 'Джакарта', name_local: 'Jakarta', lat: -6.2088, lon: 106.8456 },
  MYS: { name_en: 'Kuala Lumpur', name_ru: 'Куала-Лумпур', name_local: 'Kuala Lumpur', lat: 3.1390, lon: 101.6869 },
  SGP: { name_en: 'Singapore', name_ru: 'Сингапур', name_local: 'Singapore', lat: 1.3521, lon: 103.8198 },
  PHL: { name_en: 'Manila', name_ru: 'Манила', name_local: 'Maynila', lat: 14.5995, lon: 120.9842 },
  TWN: { name_en: 'Taipei', name_ru: 'Тайбэй', name_local: '臺北', lat: 25.0330, lon: 121.5654 },
  HKG: { name_en: 'Hong Kong', name_ru: 'Гонконг', name_local: '香港', lat: 22.3193, lon: 114.1694 },
  MAC: { name_en: 'Macau', name_ru: 'Макао', name_local: '澳門', lat: 22.1987, lon: 113.5439 },
  PAK: { name_en: 'Islamabad', name_ru: 'Исламабад', name_local: 'اسلام آباد', lat: 33.6844, lon: 73.0479 },
  AFG: { name_en: 'Kabul', name_ru: 'Кабул', name_local: 'کابل', lat: 34.5553, lon: 69.2075 },
  IRQ: { name_en: 'Baghdad', name_ru: 'Багдад', name_local: 'بغداد', lat: 33.3152, lon: 44.3661 },
  SYR: { name_en: 'Damascus', name_ru: 'Дамаск', name_local: 'دمشق', lat: 33.5138, lon: 36.2765 },
  LBN: { name_en: 'Beirut', name_ru: 'Бейрут', name_local: 'بيروت', lat: 33.8938, lon: 35.5018 },
  JOR: { name_en: 'Amman', name_ru: 'Амман', name_local: 'عمّان', lat: 31.9539, lon: 35.9106 },
  KWT: { name_en: 'Kuwait City', name_ru: 'Эль-Кувейт', name_local: 'مدينة الكويت', lat: 29.3759, lon: 47.9774 },
  ARE: { name_en: 'Abu Dhabi', name_ru: 'Абу-Даби', name_local: 'أبو ظبي', lat: 24.4539, lon: 54.3773 },
  OMN: { name_en: 'Muscat', name_ru: 'Маскат', name_local: 'مسقط', lat: 23.5880, lon: 58.3829 },
  QAT: { name_en: 'Doha', name_ru: 'Доха', name_local: 'الدوحة', lat: 25.2854, lon: 51.5310 },
  BHR: { name_en: 'Manama', name_ru: 'Манама', name_local: 'المنامة', lat: 26.2285, lon: 50.5860 },
  YEM: { name_en: 'Sanaa', name_ru: 'Сана', name_local: 'صنعاء', lat: 15.3694, lon: 44.1910 },
  ETH: { name_en: 'Addis Ababa', name_ru: 'Аддис-Абеба', name_local: 'አዲስ አበባ', lat: 9.0320, lon: 38.7469 },
  KEN: { name_en: 'Nairobi', name_ru: 'Найроби', name_local: 'Nairobi', lat: -1.2864, lon: 36.8172 },
  NGA: { name_en: 'Abuja', name_ru: 'Абуджа', name_local: 'Abuja', lat: 9.0765, lon: 7.3986 },
  MAR: { name_en: 'Rabat', name_ru: 'Рабат', name_local: 'الرباط', lat: 34.0209, lon: -6.8416 },
  DZA: { name_en: 'Algiers', name_ru: 'Алжир', name_local: 'الجزائر', lat: 36.7538, lon: 3.0588 },
  TUN: { name_en: 'Tunis', name_ru: 'Тунис', name_local: 'تونس', lat: 36.8065, lon: 10.1815 },
  LBY: { name_en: 'Tripoli', name_ru: 'Триполи', name_local: 'طرابلس', lat: 32.8872, lon: 13.1913 },
  SDN: { name_en: 'Khartoum', name_ru: 'Хартум', name_local: 'الخرطوم', lat: 15.5007, lon: 32.5599 },
  SSD: { name_en: 'Juba', name_ru: 'Джуба', name_local: 'Juba', lat: 4.8594, lon: 31.5713 },
  ERI: { name_en: 'Asmara', name_ru: 'Асмэра', name_local: 'ኣስመራ', lat: 15.3229, lon: 38.9251 },
  SOM: { name_en: 'Mogadishu', name_ru: 'Могадишо', name_local: 'Muqdisho', lat: 2.0469, lon: 45.3182 },
  UGA: { name_en: 'Kampala', name_ru: 'Кампала', name_local: 'Kampala', lat: 0.3476, lon: 32.5825 },
  TZA: { name_en: 'Dodoma', name_ru: 'Додома', name_local: 'Dodoma', lat: -6.1630, lon: 35.7516 },
  GHA: { name_en: 'Accra', name_ru: 'Аккра', name_local: 'Accra', lat: 5.6037, lon: -0.1870 },
  CIV: { name_en: 'Yamoussoukro', name_ru: 'Ямусукро', name_local: 'Yamoussoukro', lat: 6.8276, lon: -5.2893 },
  SEN: { name_en: 'Dakar', name_ru: 'Дакар', name_local: 'Dakar', lat: 14.7167, lon: -17.4677 },
  MLI: { name_en: 'Bamako', name_ru: 'Бамако', name_local: 'Bamako', lat: 12.6392, lon: -8.0029 },
  NER: { name_en: 'Niamey', name_ru: 'Ниамей', name_local: 'Niamey', lat: 13.5116, lon: 2.1254 },
  TCD: { name_en: 'Ndjamena', name_ru: 'Нджамена', name_local: 'Ndjamena', lat: 12.1348, lon: 15.0557 },
  CMR: { name_en: 'Yaounde', name_ru: 'Яунде', name_local: 'Yaounde', lat: 3.8480, lon: 11.5021 },
  CAF: { name_en: 'Bangui', name_ru: 'Банги', name_local: 'Bangui', lat: 4.3947, lon: 18.5582 },
  COG: { name_en: 'Brazzaville', name_ru: 'Браззавиль', name_local: 'Brazzaville', lat: -4.2634, lon: 15.2429 },
  COD: { name_en: 'Kinshasa', name_ru: 'Киншаса', name_local: 'Kinshasa', lat: -4.4419, lon: 15.2663 },
  AGO: { name_en: 'Luanda', name_ru: 'Луанда', name_local: 'Luanda', lat: -8.8390, lon: 13.2894 },
  ZMB: { name_en: 'Lusaka', name_ru: 'Лусака', name_local: 'Lusaka', lat: -15.3875, lon: 28.3228 },
  ZWE: { name_en: 'Harare', name_ru: 'Хараре', name_local: 'Harare', lat: -17.8252, lon: 31.0335 },
  MOZ: { name_en: 'Maputo', name_ru: 'Мапуту', name_local: 'Maputo', lat: -25.9692, lon: 32.5732 },
  MWI: { name_en: 'Lilongwe', name_ru: 'Лилонгве', name_local: 'Lilongwe', lat: -13.9626, lon: 33.7741 },
  BWA: { name_en: 'Gaborone', name_ru: 'Габороне', name_local: 'Gaborone', lat: -24.6282, lon: 25.9231 },
  NAM: { name_en: 'Windhoek', name_ru: 'Виндхук', name_local: 'Windhoek', lat: -22.5609, lon: 17.0658 },
  CHL: { name_en: 'Santiago', name_ru: 'Сантьяго', name_local: 'Santiago', lat: -33.4489, lon: -70.6693 },
  COL: { name_en: 'Bogota', name_ru: 'Богота', name_local: 'Bogota', lat: 4.7110, lon: -74.0721 },
  VEN: { name_en: 'Caracas', name_ru: 'Каракас', name_local: 'Caracas', lat: 10.4806, lon: -66.9036 },
  PER: { name_en: 'Lima', name_ru: 'Лима', name_local: 'Lima', lat: -12.0464, lon: -77.0428 },
  ECU: { name_en: 'Quito', name_ru: 'Кито', name_local: 'Quito', lat: -0.1807, lon: -78.4678 },
  BOL: { name_en: 'Sucre', name_ru: 'Сукре', name_local: 'Sucre', lat: -19.0196, lon: -65.2619 },
  PRY: { name_en: 'Asuncion', name_ru: 'Асунсьон', name_local: 'Asuncion', lat: -25.2637, lon: -57.5759 },
  URY: { name_en: 'Montevideo', name_ru: 'Монтевидео', name_local: 'Montevideo', lat: -34.9011, lon: -56.1645 },
  CUB: { name_en: 'Havana', name_ru: 'Гавана', name_local: 'La Habana', lat: 23.1136, lon: -82.3666 },
  JAM: { name_en: 'Kingston', name_ru: 'Кингстон', name_local: 'Kingston', lat: 17.9714, lon: -76.7931 },
  HTI: { name_en: 'Port-au-Prince', name_ru: 'Порт-о-Пренс', name_local: 'Port-au-Prince', lat: 18.5944, lon: -72.3074 },
  DOM: { name_en: 'Santo Domingo', name_ru: 'Санто-Доминго', name_local: 'Santo Domingo', lat: 18.4861, lon: -69.9312 },
  GTM: { name_en: 'Guatemala City', name_ru: 'Гватемала', name_local: 'Guatemala', lat: 14.6349, lon: -90.5069 },
  HND: { name_en: 'Tegucigalpa', name_ru: 'Тегусигальпа', name_local: 'Tegucigalpa', lat: 14.0723, lon: -87.1921 },
  SLV: { name_en: 'San Salvador', name_ru: 'Сан-Сальвадор', name_local: 'San Salvador', lat: 13.6929, lon: -89.2182 },
  NIC: { name_en: 'Managua', name_ru: 'Манагуа', name_local: 'Managua', lat: 12.1149, lon: -86.2362 },
  CRI: { name_en: 'San Jose', name_ru: 'Сан-Хосе', name_local: 'San Jose', lat: 9.9281, lon: -84.0907 },
  PAN: { name_en: 'Panama City', name_ru: 'Панама', name_local: 'Panama', lat: 8.9824, lon: -79.5199 },
  NZL: { name_en: 'Wellington', name_ru: 'Веллингтон', name_local: 'Wellington', lat: -41.2865, lon: 174.7762 },
  FJI: { name_en: 'Suva', name_ru: 'Сува', name_local: 'Suva', lat: -18.1416, lon: 178.4419 },
  PNG: { name_en: 'Port Moresby', name_ru: 'Порт-Морсби', name_local: 'Port Moresby', lat: -9.4438, lon: 147.1803 }
};
