export const financialLayers = {
  vix: { name: 'VIX (Индекс страха)', category: 'financial', icon: '📈', color: '#ff0000', visualizationType: 'marker', defaultLat: 40.7128, defaultLng: -74.0060 },
  'gold-oil': { name: 'Золото/Нефть', category: 'financial', icon: '🥇', color: '#ffaa00', visualizationType: 'marker', defaultLat: 51.5074, defaultLng: -0.1278 },
  'copper-gold': { name: 'Медь/Золото', category: 'financial', icon: '🔶', color: '#cc8800', visualizationType: 'marker', defaultLat: 51.5074, defaultLng: -0.1278 },
  bdi: { name: 'BDI (Балтийский индекс)', category: 'financial', icon: '🚢', color: '#0088ff', visualizationType: 'marker', defaultLat: 55.6761, defaultLng: 12.5683 },
  'yield-curve': { name: 'Кривая доходности', category: 'financial', icon: '📉', color: '#ff44ff', visualizationType: 'marker', defaultLat: 38.8895, defaultLng: -77.0353 },
  dxy: { name: 'Индекс доллара DXY', category: 'financial', icon: '💵', color: '#00cc88', visualizationType: 'marker', defaultLat: 40.7128, defaultLng: -74.0060 },
  tips: { name: 'Реальные ставки TIPS', category: 'financial', icon: '📊', color: '#ff66aa', visualizationType: 'marker', defaultLat: 38.8895, defaultLng: -77.0353 },
  ovx: { name: 'Волатильность нефти OVX', category: 'financial', icon: '🛢️', color: '#ff6600', visualizationType: 'marker', defaultLat: 40.7128, defaultLng: -74.0060 },
  'hy-spread': { name: 'Корпоративные спреды', category: 'financial', icon: '🏦', color: '#ff4400', visualizationType: 'marker', defaultLat: 40.7128, defaultLng: -74.0060 },
  uranium: { name: 'Цена урана', category: 'financial', icon: '☢️', color: '#44ff44', visualizationType: 'marker', defaultLat: 51.5074, defaultLng: -0.1278 },
  'crypto-fear': { name: 'Крипто-страх', category: 'financial', icon: '₿', color: '#ff8800', visualizationType: 'marker', defaultLat: 37.7749, defaultLng: -122.4194 },
  'sp500-vix': { name: 'S&P/VIX', category: 'financial', icon: '📊', color: '#44aaff', visualizationType: 'marker', defaultLat: 40.7128, defaultLng: -74.0060 },
  'big-mac': { name: 'Индекс Биг-Мак', category: 'financial', icon: '🍔', color: '#ff6600', visualizationType: 'choropleth' },
  'big-mac-alt': { name: 'Биг-Мак (альт.)', category: 'financial', icon: '🍔', color: '#ff8800', visualizationType: 'choropleth' },
  'big-mac-main': { name: 'Биг-Мак (осн.)', category: 'financial', icon: '🍔', color: '#ffaa00', visualizationType: 'choropleth' },
  vxx: { name: 'VXX (Волатильность)', category: 'financial', icon: '📉', color: '#ff44aa', visualizationType: 'marker', defaultLat: 40.7128, defaultLng: -74.0060 },
  'gold-silver': { name: 'Золото/Серебро', category: 'financial', icon: '🥇', color: '#ffcc44', visualizationType: 'marker', defaultLat: 51.5074, defaultLng: -0.1278 },
  'debt-gdp': { name: 'Долг/ВВП', category: 'financial', icon: '💰', color: '#ff4444', visualizationType: 'choropleth' },
  ofac: { name: 'OFAC Санкции', category: 'financial', icon: '⛔', color: '#ff2200', visualizationType: 'choropleth' },
};
