export const otherLayers = {
  weather: { name: 'Погода', category: 'other', icon: '⛅', color: '#00ccff', visualizationType: 'marker' },
  hurricanes: { name: 'Ураганы', category: 'other', icon: '🌀', color: '#ff8800', visualizationType: 'marker' },
  'earthquakes-other': { name: 'Землетрясения', category: 'other', icon: '🌋', color: '#ff6600', visualizationType: 'marker' },
  volcanoes: { name: 'Вулканы', category: 'other', icon: '🌋', color: '#ff4400', visualizationType: 'marker' },
  wildfires: { name: 'Лесные пожары', category: 'other', icon: '🔥', color: '#ff2200', visualizationType: 'marker' },
  drought: { name: 'Засуха', category: 'other', icon: '🏜️', color: '#ffaa00', visualizationType: 'choropleth' },
  democracy: { name: 'Индекс демократии', category: 'other', icon: '🗳️', color: '#44ccff', visualizationType: 'choropleth' },
  corruption: { name: 'Индекс коррупции', category: 'other', icon: '💰', color: '#ff4444', visualizationType: 'choropleth' },
  freedom: { name: 'Индекс свободы', category: 'other', icon: '🕊️', color: '#44ff44', visualizationType: 'choropleth' },
  'press-freedom': { name: 'Свобода прессы', category: 'other', icon: '📰', color: '#44ccff', visualizationType: 'choropleth' },
  internet: { name: 'Интернет-доступ', category: 'other', icon: '🌐', color: '#44aaff', visualizationType: 'choropleth' },
  mobile: { name: 'Мобильная связь', category: 'other', icon: '📱', color: '#44cc44', visualizationType: 'choropleth' },
  education: { name: 'Образование', category: 'other', icon: '🎓', color: '#44ff88', visualizationType: 'choropleth' },
  healthcare: { name: 'Здравоохранение', category: 'other', icon: '🏥', color: '#ff44aa', visualizationType: 'choropleth' },
  'military-spending': { name: 'Военные расходы', category: 'other', icon: '💰', color: '#ff4400', visualizationType: 'choropleth' },
  'trade-balance': { name: 'Торговый баланс', category: 'other', icon: '📊', color: '#ffaa00', visualizationType: 'choropleth' },
  poverty: { name: 'Бедность', category: 'other', icon: '📉', color: '#ff4444', visualizationType: 'choropleth' },
  inequality: { name: 'Неравенство', category: 'other', icon: '⚖️', color: '#ff8800', visualizationType: 'choropleth' },
  hdi: { name: 'Индекс человеческого развития', category: 'other', icon: '📊', color: '#44cc44', visualizationType: 'choropleth' },
};
