apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crucix

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment-crucix.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - cronjob.yaml
  - statefulset-python.yaml
  # - servicemonitor.yaml  # раскомментировать, если установлен Prometheus Operator

commonLabels:
  app.kubernetes.io/part-of: crucix-core
  app.kubernetes.io/managed-by: kustomize

images:
  - name: crucix-core
    newTag: 3.0.0
  - name: crucix-python
    newTag: 1.0.0

replicas:
  - name: crucix-core
    count: 3
