// apis/predict/models/vae.mjs
// Variational Autoencoder (Kingma & Welling, 2013)

function xavier(rows, cols, seed = 42) { const scale = Math.sqrt(2 / (rows + cols)); const W = []; let s = seed; const rand = () => { s = (s * 9301 + 49297) % 233280; return s / 233280; }; for (let i = 0; i < cols; i++) { const col = new Float64Array(rows); for (let j = 0; j < rows; j++) { const u1 = rand(), u2 = rand(); const z = Math.sqrt(-2 * Math.log(u1 + 1e-10)) * Math.cos(2 * Math.PI * u2); col[j] = z * scale; } W.push(col); } return W; }
function gaussianSample() { const u1 = Math.random(), u2 = Math.random(); return Math.sqrt(-2 * Math.log(u1 + 1e-10)) * Math.cos(2 * Math.PI * u2); }
function euclideanDist(a, b) { let s = 0; for (let i = 0; i < a.length; i++) s += (a[i] - b[i]) ** 2; return Math.sqrt(s); }

class DenseLayer {
  constructor(inDim, outDim, activation = 'linear', seed = 42) { this.inDim = inDim; this.outDim = outDim; this.activation = activation; this.W = xavier(inDim, outDim, seed); this.b = new Float64Array(outDim).fill(0); this.mW = this.W.map(row => new Float64Array(row.length)); this.vW = this.W.map(row => new Float64Array(row.length)); this.mb = new Float64Array(outDim); this.vb = new Float64Array(outDim); this.t = 0; }
  forward(x) { const z = new Float64Array(this.outDim); for (let o = 0; o < this.outDim; o++) { let sum = this.b[o]; for (let i = 0; i < this.inDim; i++) sum += x[i] * this.W[o][i]; z[o] = sum; } let a; if (this.activation === 'relu') a = z.map(v => Math.max(0, v)); else if (this.activation === 'sigmoid') a = z.map(v => 1 / (1 + Math.exp(-v))); else if (this.activation === 'tanh') a = z.map(v => Math.tanh(v)); else a = Array.from(z); return { z, a, input: x }; }
  backward(dA, cache) { const { z, a, input } = cache; const dz = new Float64Array(this.outDim); for (let o = 0; o < this.outDim; o++) { if (this.activation === 'relu') dz[o] = z[o] > 0 ? dA[o] : 0; else if (this.activation === 'sigmoid') dz[o] = dA[o] * a[o] * (1 - a[o]); else if (this.activation === 'tanh') dz[o] = dA[o] * (1 - a[o] * a[o]); else dz[o] = dA[o]; } const dW = this.W.map(row => new Float64Array(row.length)); const db = new Float64Array(this.outDim); for (let o = 0; o < this.outDim; o++) { for (let i = 0; i < this.inDim; i++) dW[o][i] = dz[o] * input[i]; db[o] = dz[o]; } const dInput = new Float64Array(this.inDim); for (let i = 0; i < this.inDim; i++) { let sum = 0; for (let o = 0; o < this.outDim; o++) sum += dz[o] * this.W[o][i]; dInput[i] = sum; } return { dInput, dW, db }; }
  update(dW, db, lr = 0.001, beta1 = 0.9, beta2 = 0.999, eps = 1e-8) { this.t++; for (let o = 0; o < this.outDim; o++) { for (let i = 0; i < this.inDim; i++) { this.mW[o][i] = beta1 * this.mW[o][i] + (1 - beta1) * dW[o][i]; this.vW[o][i] = beta2 * this.vW[o][i] + (1 - beta2) * dW[o][i] * dW[o][i]; const mHat = this.mW[o][i] / (1 - Math.pow(beta1, this.t)); const vHat = this.vW[o][i] / (1 - Math.pow(beta2, this.t)); this.W[o][i] -= lr * mHat / (Math.sqrt(vHat) + eps); } this.mb[o] = beta1 * this.mb[o] + (1 - beta1) * db[o]; this.vb[o] = beta2 * this.vb[o] + (1 - beta2) * db[o] * db[o]; const mHat = this.mb[o] / (1 - Math.pow(beta1, this.t)); const vHat = this.vb[o] / (1 - Math.pow(beta2, this.t)); this.b[o] -= lr * mHat / (Math.sqrt(vHat) + eps); } }
}

class VAE {
  constructor({ inputDim = 10, encoderDims = [32, 16], latentDim = 4, decoderDims = [16, 32], seed = 42 }) { this.inputDim = inputDim; this.encoderDims = encoderDims; this.latentDim = latentDim; this.decoderDims = decoderDims; this.encoderLayers = []; let prevDim = inputDim; for (let i = 0; i < encoderDims.length; i++) { this.encoderLayers.push(new DenseLayer(prevDim, encoderDims[i], 'relu', seed + i * 10)); prevDim = encoderDims[i]; } this.muLayer = new DenseLayer(prevDim, latentDim, 'linear', seed + 100); this.logvarLayer = new DenseLayer(prevDim, latentDim, 'linear', seed + 110); this.decoderLayers = []; prevDim = latentDim; for (let i = 0; i < decoderDims.length; i++) { this.decoderLayers.push(new DenseLayer(prevDim, decoderDims[i], 'relu', seed + 200 + i * 10)); prevDim = decoderDims[i]; } this.outputLayer = new DenseLayer(prevDim, inputDim, 'linear', seed + 300); }
  encode(x) { let h = x; const encoderCaches = []; for (const layer of this.encoderLayers) { const result = layer.forward(h); encoderCaches.push(result); h = result.a; } const muResult = this.muLayer.forward(h); const logvarResult = this.logvarLayer.forward(h); return { mu: muResult.a, logvar: logvarResult.a, hidden: h, caches: { encoder: encoderCaches, mu: muResult, logvar: logvarResult } }; }
  reparameterize(mu, logvar) { const sigma = logvar.map(lv => Math.exp(0.5 * lv)); const epsilon = Array.from({ length: this.latentDim }, () => gaussianSample()); const z = mu.map((m, i) => m + sigma[i] * epsilon[i]); return { z, sigma, epsilon }; }
  decode(z) { let h = z; const decoderCaches = []; for (const layer of this.decoderLayers) { const result = layer.forward(h); decoderCaches.push(result); h = result.a; } const outputResult = this.outputLayer.forward(h); return { output: outputResult.a, caches: { decoder: decoderCaches, output: outputResult } }; }
  forward(x) { const enc = this.encode(x); const { z, sigma, epsilon } = this.reparameterize(enc.mu, enc.logvar); const dec = this.decode(z); let reconLoss = 0; for (let i = 0; i < this.inputDim; i++) reconLoss += (dec.output[i] - x[i]) ** 2; reconLoss /= this.inputDim; let klLoss = 0; for (let i = 0; i < this.latentDim; i++) klLoss += -0.5 * (1 + enc.logvar[i] - enc.mu[i] ** 2 - Math.exp(enc.logvar[i])); const totalLoss = reconLoss + klLoss; return { reconstruction: dec.output, mu: enc.mu, logvar: enc.logvar, z, loss: { reconLoss, klLoss, totalLoss }, caches: { encoder: enc.caches, decoder: dec.caches, z, mu: enc.mu, logvar: enc.logvar, sigma, epsilon, input: x } }; }
  backward(forwardResult) { const { caches } = forwardResult; const { input, z, mu, logvar, sigma, epsilon } = caches; const dOutput = new Float64Array(this.inputDim); for (let i = 0; i < this.inputDim; i++) dOutput[i] = 2 * (forwardResult.reconstruction[i] - input[i]) / this.inputDim; const decoderGrads = []; let dH = dOutput; const outputGrads = this.outputLayer.backward(dH, caches.decoder.output); dH = outputGrads.dInput; for (let i = this.decoderLayers.length - 1; i >= 0; i--) { const grads = this.decoderLayers[i].backward(dH, caches.decoder.decoder[i]); decoderGrads.unshift(grads); dH = grads.dInput; } const dZ = dH; const dMu = new Float64Array(this.latentDim); const dLogvarReparam = new Float64Array(this.latentDim); for (let i = 0; i < this.latentDim; i++) { dMu[i] = dZ[i]; dLogvarReparam[i] = 0.5 * sigma[i] * epsilon[i] * dZ[i]; } const dMuKL = new Float64Array(this.latentDim); const dLogvarKL = new Float64Array(this.latentDim); for (let i = 0; i < this.latentDim; i++) { dMuKL[i] = mu[i]; dLogvarKL[i] = 0.5 * (1 - Math.exp(logvar[i])); } const dMuTotal = dMu.map((v, i) => v + dMuKL[i]); const dLogvarTotal = dLogvarReparam.map((v, i) => v + dLogvarKL[i]); const muGrads = this.muLayer.backward(dMuTotal, caches.encoder.mu); const logvarGrads = this.logvarLayer.backward(dLogvarTotal, caches.encoder.logvar); const dHidden = new Float64Array(muGrads.dInput.length); for (let i = 0; i < dHidden.length; i++) dHidden[i] = muGrads.dInput[i] + logvarGrads.dInput[i]; const encoderGrads = []; dH = dHidden; for (let i = this.encoderLayers.length - 1; i >= 0; i--) { const grads = this.encoderLayers[i].backward(dH, caches.encoder.encoder[i]); encoderGrads.unshift(grads); dH = grads.dInput; } return { encoderGrads, muGrads, logvarGrads, decoderGrads, outputGrads }; }
  updateWeights(grads, lr = 0.001) { for (let i = 0; i < this.encoderLayers.length; i++) this.encoderLayers[i].update(grads.encoderGrads[i].dW, grads.encoderGrads[i].db, lr); this.muLayer.update(grads.muGrads.dW, grads.muGrads.db, lr); this.logvarLayer.update(grads.logvarGrads.dW, grads.logvarGrads.db, lr); for (let i = 0; i < this.decoderLayers.length; i++) this.decoderLayers[i].update(grads.decoderGrads[i].dW, grads.decoderGrads[i].db, lr); this.outputLayer.update(grads.outputGrads.dW, grads.outputGrads.db, lr); }
  fit(X, { epochs = 100, batchSize = 16, lr = 0.001, beta = 1.0, verbose = false } = {}) { const n = X.length; const history = []; for (let epoch = 0; epoch < epochs; epoch++) { const indices = Array.from({ length: n }, (_, i) => i); for (let i = n - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [indices[i], indices[j]] = [indices[j], indices[i]]; } let epochRecon = 0, epochKL = 0, batchCount = 0; for (let start = 0; start < n; start += batchSize) { const batchIdx = indices.slice(start, start + batchSize); let batchRecon = 0, batchKL = 0; for (const idx of batchIdx) { const x = X[idx]; const fwd = this.forward(x); batchRecon += fwd.loss.reconLoss; batchKL += beta * fwd.loss.klLoss; const grads = this.backward(fwd); this.updateWeights(grads, lr / batchIdx.length); } epochRecon += batchRecon / batchIdx.length; epochKL += batchKL / batchIdx.length; batchCount++; } const avgRecon = epochRecon / batchCount; const avgKL = epochKL / batchCount; const totalLoss = avgRecon + avgKL; history.push({ epoch, reconLoss: avgRecon, klLoss: avgKL, totalLoss }); if (verbose && epoch % 10 === 0) console.log(`Epoch ${epoch}: recon=${avgRecon.toFixed(5)}, kl=${avgKL.toFixed(5)}`); } return { history, finalLoss: history[history.length - 1].totalLoss }; }
  encode_only(x) { return this.encode(x).mu; }
  generate(z = null) { const latent = z || Array.from({ length: this.latentDim }, () => gaussianSample()); const dec = this.decode(latent); return { sample: dec.output, latent }; }
  interpolate(x1, x2, steps = 5) { const z1 = this.encode_only(x1); const z2 = this.encode_only(x2); const results = []; for (let s = 0; s <= steps; s++) { const t = s / steps; const z = z1.map((v, i) => v * (1 - t) + z2[i] * t); const dec = this.decode(z); results.push({ t, sample: dec.output, latent: z }); } return results; }
}

function clusterLatentSpace(latentSpace, k = 3) { if (latentSpace.length < k) return []; const centroids = [latentSpace[Math.floor(Math.random() * latentSpace.length)]]; while (centroids.length < k) { const distances = latentSpace.map(x => Math.min(...centroids.map(c => euclideanDist(x, c)))); const sum = distances.reduce((a, b) => a + b, 0); let r = Math.random() * sum; for (let i = 0; i < latentSpace.length; i++) { r -= distances[i]; if (r <= 0) { centroids.push(latentSpace[i]); break; } } } let assignments = new Array(latentSpace.length).fill(0); for (let iter = 0; iter < 20; iter++) { assignments = latentSpace.map(x => { let best = 0, bestDist = Infinity; for (let c = 0; c < centroids.length; c++) { const d = euclideanDist(x, centroids[c]); if (d < bestDist) { bestDist = d; best = c; } } return best; }); for (let c = 0; c < k; c++) { const members = latentSpace.filter((_, i) => assignments[i] === c); if (members.length === 0) continue; for (let d = 0; d < centroids[c].length; d++) centroids[c][d] = members.reduce((s, m) => s + m[d], 0) / members.length; } } const clusterSizes = new Array(k).fill(0); for (const a of assignments) clusterSizes[a]++; return { centroids, assignments, sizes: clusterSizes, distribution: clusterSizes.map(s => s / latentSpace.length) }; }

function crucixVAE(history, { epochs = 50, latentDim = 4 } = {}) { const X = []; for (const h of history) X.push([(h.fred?.vix || 20) / 50, (h.fred?.hySpread || 3) / 10, (h.fred?.treasury10y || 4) / 6, (h.gdelt?.conflictEvents?.length || 0) / 20, (h.sanctions?.count || 0) / 5, (h.energy?.oilPrice || 70) / 120, (h.gold?.price || 1900) / 2200, (h.dxy?.value || 100) / 110, h.radiation ? Math.max(...Object.values(h.radiation).map(s => s.cpm || 0)) / 200 : 0, (h.delta?.newAlerts || 0) / 10]); if (X.length < 30) return { error: 'Мало данных', count: X.length }; const model = new VAE({ inputDim: 10, encoderDims: [32, 16], latentDim, decoderDims: [16, 32] }); const trainResult = model.fit(X, { epochs, batchSize: 16, lr: 0.001 }); const latentSpace = X.map(x => model.encode_only(x)); const currentLatent = model.encode_only(X[X.length - 1]); const reconstruction = model.forward(X[X.length - 1]); const reconstructionErrors = X.map((x, i) => { const fwd = model.forward(x); let err = 0; for (let j = 0; j < x.length; j++) err += (fwd.reconstruction[j] - x[j]) ** 2; return Math.sqrt(err / x.length); }); const avgReconError = reconstructionErrors.reduce((a, b) => a + b, 0) / reconstructionErrors.length; const scenarios = []; for (let i = 0; i < 5; i++) scenarios.push(model.generate().sample); return { model, latentDim, latentSpace, currentLatent, reconstruction: reconstruction.reconstruction, reconstructionError: avgReconError, scenarios, trainingLoss: trainResult.finalLoss, interpretation: avgReconError < 0.1 ? 'система хорошо вписана в латентное пространство' : 'высокая ошибка реконструкции — необычное состояние', latentClusters: clusterLatentSpace(latentSpace, 3) }; }

export { VAE, DenseLayer, crucixVAE, clusterLatentSpace };
