// apis/predict/federated/fl_protocol.mjs
// Federated Learning Protocol: FedAvg + Differential Privacy

function federatedAveraging(updates, weights = null) { if (updates.length === 0) return null; const nModels = updates.length; const totalSamples = updates.reduce((s, u) => s + (u.nSamples || 1), 0); const normalizedWeights = weights || updates.map(u => (u.nSamples || 1) / totalSamples); const firstModel = updates[0].model; const structure = getModelStructure(firstModel); const averaged = deepCloneStructure(firstModel); applyAveraging(averaged, updates.map(u => u.model), normalizedWeights, structure); return averaged; }
function getModelStructure(model) { const structure = {}; if (model.W) { structure.W = model.W.map(Wl => Wl.map(row => row.length)); structure.b = model.b.map(bl => bl.length); structure.type = 'MLP'; } else if (model.weights) { structure.weights = model.weights.map(Wl => Wl.map(row => row.length)); structure.biases = model.biases.map(bl => bl.length); structure.type = 'GCN'; } else if (model.trees) structure.type = 'Ensemble'; else if (model.layers) { structure.layers = model.layers.map(l => ({ W: l.W.map(row => row.length), b: l.b.length })); structure.type = 'DenseNet'; } return structure; }
function deepCloneStructure(model) { if (model.W) return { W: model.W.map(Wl => Wl.map(row => new Float64Array(row))), b: model.b.map(bl => new Float64Array(bl)), layers: model.layers, activation: model.activation, outputActivation: model.outputActivation }; if (model.weights) return { weights: model.weights.map(Wl => Wl.map(row => new Float64Array(row))), biases: model.biases.map(bl => new Float64Array(bl)) }; return {}; }
function applyAveraging(target, sources, weights, structure) { if (structure.type === 'MLP') { for (let l = 0; l < target.W.length; l++) { for (let i = 0; i < target.W[l].length; i++) { for (let j = 0; j < target.W[l][i].length; j++) { target.W[l][i][j] = 0; for (let k = 0; k < sources.length; k++) target.W[l][i][j] += weights[k] * sources[k].W[l][i][j]; } } for (let i = 0; i < target.b[l].length; i++) { target.b[l][i] = 0; for (let k = 0; k < sources.length; k++) target.b[l][i] += weights[k] * sources[k].b[l][i]; } } } }
function addDifferentialPrivacy(model, epsilon = 1.0, sensitivity = 0.1) { const scale = sensitivity / epsilon; if (model.W) { for (let l = 0; l < model.W.length; l++) { for (let i = 0; i < model.W[l].length; i++) { for (let j = 0; j < model.W[l][i].length; j++) model.W[l][i][j] += laplaceSample(0, scale); } for (let i = 0; i < model.b[l].length; i++) model.b[l][i] += laplaceSample(0, scale); } } return model; }
function addGaussianPrivacy(model, epsilon = 1.0, delta = 1e-5, sensitivity = 0.1) { const sigma = sensitivity * Math.sqrt(2 * Math.log(1.25 / delta)) / epsilon; if (model.W) { for (let l = 0; l < model.W.length; l++) { for (let i = 0; i < model.W[l].length; i++) { for (let j = 0; j < model.W[l][i].length; j++) model.W[l][i][j] += gaussianSample(0, sigma); } for (let i = 0; i < model.b[l].length; i++) model.b[l][i] += gaussianSample(0, sigma); } } return model; }
function laplaceSample(loc = 0, scale = 1) { const u = Math.random() - 0.5; return loc - scale * Math.sign(u) * Math.log(1 - 2 * Math.abs(u)); }
function gaussianSample(mean = 0, std = 1) { const u1 = Math.random(), u2 = Math.random(); return mean + std * Math.sqrt(-2 * Math.log(u1 + 1e-10)) * Math.cos(2 * Math.PI * u2); }
function generateMaskingPair(seed, shape) { let s = seed; const rand = () => { s = (s * 9301 + 49297) % 233280; return s / 233280 - 0.5; }; const mask = shape.map(dims => dims.map(d => { const arr = new Float64Array(d); for (let i = 0; i < d; i++) arr[i] = rand() * 0.001; return arr; })); const negMask = mask.map(Wl => Wl.map(row => row.map(v => -v))); return { mask, negMask }; }
class FederatedClient { constructor({ clientId, model, data }) { this.clientId = clientId; this.model = model; this.data = data; this.rounds = 0; this.totalSamples = data.X ? data.X.length : 0; } async localTrain({ epochs = 5, lr = 0.001 } = {}) { const result = this.model.fit(this.data.X, this.data.y, { epochs, batchSize: 16, lr, lossType: 'mse' }); this.rounds++; return { loss: result.finalLoss, nSamples: this.totalSamples }; } getWeights({ withDP = false, epsilon = 1.0 } = {}) { const weights = JSON.parse(JSON.stringify(this.model.toJSON ? this.model.toJSON() : this.model)); if (withDP) addDifferentialPrivacy(weights, epsilon, 0.1); return { clientId: this.clientId, nSamples: this.totalSamples, model: weights, rounds: this.rounds }; } setWeights(globalModel) { if (this.model.W) { this.model.W = globalModel.W.map(Wl => Wl.map(row => new Float64Array(row))); this.model.b = globalModel.b.map(bl => new Float64Array(bl)); } } }
class FederatedServer { constructor({ minClients = 3, dpEnabled = false, epsilon = 1.0 }) { this.minClients = minClients; this.dpEnabled = dpEnabled; this.epsilon = epsilon; this.globalModel = null; this.rounds = 0; this.updates = []; this.history = []; } receiveUpdate(update) { this.updates.push(update); } aggregate() { if (this.updates.length < this.minClients) return { success: false, reason: `need at least ${this.minClients} clients, have ${this.updates.length}` }; if (this.dpEnabled) for (const u of this.updates) addDifferentialPrivacy(u.model, this.epsilon); const averaged = federatedAveraging(this.updates); this.globalModel = averaged; this.rounds++; const history = { round: this.rounds, nClients: this.updates.length, totalSamples: this.updates.reduce((s, u) => s + u.nSamples, 0), avgRounds: this.updates.reduce((s, u) => s + u.rounds, 0) / this.updates.length }; this.history.push(history); this.updates = []; return { success: true, ...history, globalModel: averaged }; } broadcast() { return this.globalModel; } }
export { federatedAveraging, addDifferentialPrivacy, addGaussianPrivacy, generateMaskingPair, FederatedClient, FederatedServer, laplaceSample, gaussianSample };
