// apis/predict/exotic/chaos.mjs
// Chaos Theory: Lyapunov, correlation dimension, recurrence plots

function euclidean(a, b) { let s = 0; for (let i = 0; i < a.length; i++) s += (a[i] - b[i]) ** 2; return Math.sqrt(s); }
function linearRegressionSlope(x, y) { const n = x.length; const mx = x.reduce((a, b) => a + b, 0) / n; const my = y.reduce((a, b) => a + b, 0) / n; let num = 0, den = 0; for (let i = 0; i < n; i++) { num += (x[i] - mx) * (y[i] - my); den += (x[i] - mx) ** 2; } return den > 0 ? num / den : 0; }
function takensEmbedding(series, m, tau = 1) { const n = series.length; const embedded = []; for (let i = 0; i < n - (m - 1) * tau; i++) { const point = []; for (let j = 0; j < m; j++) point.push(series[i + j * tau]); embedded.push(point); } return embedded; }
function lyapunovExponent(series, { m = 3, tau = 1, maxIterations = 100 } = {}) { const embedded = takensEmbedding(series, m, tau); const n = embedded.length; if (n < 20) return { error: 'Мало точек', count: n }; const distances = Array.from({ length: maxIterations }, () => []); for (let i = 0; i < n; i++) { let bestDist = Infinity, bestJ = -1; for (let j = 0; j < n; j++) { if (Math.abs(i - j) < m) continue; const d = euclidean(embedded[i], embedded[j]); if (d < bestDist && d > 0) { bestDist = d; bestJ = j; } } if (bestJ === -1) continue; for (let k = 0; k < maxIterations; k++) { if (i + k >= n || bestJ + k >= n) break; const d = euclidean(embedded[i + k], embedded[bestJ + k]); if (d > 0) distances[k].push(Math.log(d)); } } const avgLog = distances.map(arr => arr.length > 0 ? arr.reduce((a, b) => a + b, 0) / arr.length : 0); const fitLen = Math.max(3, Math.floor(avgLog.length * 0.2)); const x = Array.from({ length: fitLen }, (_, i) => i); const y = avgLog.slice(0, fitLen); const slope = linearRegressionSlope(x, y); return { lyapunovExponent: slope, regime: slope > 0.05 ? 'chaotic' : slope > 0.005 ? 'weakly chaotic' : 'stable', interpretation: slope > 0.05 ? 'система хаотична' : slope > 0.005 ? 'слабо хаотичная' : 'система устойчива' }; }
function correlationDimension(series, { m = 3, tau = 1, nRadii = 20 } = {}) { const embedded = takensEmbedding(series, m, tau); const n = embedded.length; if (n < 20) return { error: 'Мало точек' }; const distances = []; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) distances.push(euclidean(embedded[i], embedded[j])); if (distances.length === 0) return { error: 'Нет пар' }; const minD = Math.min(...distances); const maxD = Math.max(...distances); const radii = [], correlations = []; for (let i = 0; i < nRadii; i++) { const r = minD * Math.pow(maxD / minD, i / (nRadii - 1)); const count = distances.filter(d => d < r).length; radii.push(r); correlations.push(count / distances.length); } const valid = []; for (let i = 0; i < radii.length; i++) if (correlations[i] > 0.01 && correlations[i] < 0.99) valid.push({ x: Math.log(radii[i]), y: Math.log(correlations[i]) }); if (valid.length < 3) return { error: 'Мало данных' }; const slope = linearRegressionSlope(valid.map(v => v.x), valid.map(v => v.y)); return { dimension: slope, interpretation: slope < 1.5 ? 'низкоразмерная динамика' : slope < 2.5 ? 'умеренная размерность' : 'высокоразмерная (шум)', radii, correlations }; }
function recurrencePlot(series, { m = 3, tau = 1, epsilon = null } = {}) { const embedded = takensEmbedding(series, m, tau); const n = embedded.length; if (n < 10) return { error: 'Мало точек' }; if (epsilon === null) { let maxD = 0; for (let i = 0; i < Math.min(n, 50); i++) for (let j = i + 1; j < Math.min(n, 50); j++) maxD = Math.max(maxD, euclidean(embedded[i], embedded[j])); epsilon = maxD * 0.1; } const R = Array.from({ length: n }, () => new Array(n).fill(0)); let recurrenceRate = 0; for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) if (euclidean(embedded[i], embedded[j]) < epsilon) { R[i][j] = 1; recurrenceRate++; } recurrenceRate /= (n * n); let diagonalPoints = 0; for (let i = 0; i < n - 2; i++) for (let j = 0; j < n - 2; j++) if (R[i][j] && R[i + 1][j + 1] && R[i + 2][j + 2]) diagonalPoints++; const determinism = diagonalPoints / Math.max(recurrenceRate * n * n, 1); return { recurrenceRate, determinism, epsilon, matrix: R, interpretation: determinism > 0.5 ? 'высокий детерминизм' : determinism > 0.2 ? 'умеренный детерминизм' : 'слабая структура' }; }
function crucixChaos(history) { const vix = history.map(h => h.fred?.vix).filter(v => v !== undefined && !isNaN(v)); if (vix.length < 50) return { error: 'Мало данных' }; const lyap = lyapunovExponent(vix, { m: 3, tau: 1 }); const corr = correlationDimension(vix, { m: 3, tau: 1 }); const recur = recurrencePlot(vix, { m: 3, tau: 1 }); return { lyapunov: lyap, correlationDimension: corr, recurrence: { recurrenceRate: recur.recurrenceRate, determinism: recur.determinism }, predictability: lyap.lyapunovExponent < 0.005 && recur.determinism > 0.3 ? 'high' : lyap.lyapunovExponent < 0.05 ? 'moderate' : 'low' }; }
export { takensEmbedding, lyapunovExponent, correlationDimension, recurrencePlot, crucixChaos, euclidean };
