// apis/predict/exotic/game_theory.mjs
// Game Theory для геополитики

function findNashEquilibria(A, B) { const nActions = A.length; const mActions = A[0].length; const equilibria = []; for (let i = 0; i < nActions; i++) { for (let j = 0; j < mActions; j++) { let isBestResponseP1 = true; for (let k = 0; k < nActions; k++) if (A[k][j] > A[i][j]) { isBestResponseP1 = false; break; } let isBestResponseP2 = true; for (let k = 0; k < mActions; k++) if (B[i][k] > B[i][j]) { isBestResponseP2 = false; break; } if (isBestResponseP1 && isBestResponseP2) equilibria.push({ type: 'pure', action1: i, action2: j, payoff1: A[i][j], payoff2: B[i][j] }); } } return equilibria; }
function mixedNash2x2(A, B) { const a11 = A[0][0], a12 = A[0][1], a21 = A[1][0], a22 = A[1][1]; const b11 = B[0][0], b12 = B[0][1], b21 = B[1][0], b22 = B[1][1]; const denomQ = (a11 - a12 - a21 + a22); const q = denomQ !== 0 ? (a22 - a12) / denomQ : 0.5; const denomP = (b11 - b21 - b12 + b22); const p = denomP !== 0 ? (b22 - b21) / denomP : 0.5; if (p >= 0 && p <= 1 && q >= 0 && q <= 1) return { type: 'mixed', p, q, payoff1: p * (q * a11 + (1 - q) * a12) + (1 - p) * (q * a21 + (1 - q) * a22), payoff2: q * (p * b11 + (1 - p) * b21) + (1 - q) * (p * b12 + (1 - p) * b22) }; return null; }
function evolutionarilyStableStrategy(A) { const a11 = A[0][0], a12 = A[0][1], a21 = A[1][0], a22 = A[1][1]; const strategies = []; if (a11 > a21) strategies.push({ type: 'pure', strategy: 0, condition: 'A11 > A21' }); if (a22 > a12) strategies.push({ type: 'pure', strategy: 1, condition: 'A22 > A12' }); const p = (a22 - a12) / (a11 - a12 - a21 + a22); if (p > 0 && p < 1) strategies.push({ type: 'mixed', probability: p, condition: 'interior ESS' }); return strategies; }
function prisonersDilemmaTournament(strategies, rounds = 200, iterations = 100) { const T = 5, R = 3, P = 1, S = 0; const scores = {}; for (const s of strategies) scores[s.name] = 0; for (let iter = 0; iter < iterations; iter++) { for (let i = 0; i < strategies.length; i++) { for (let j = i; j < strategies.length; j++) { const s1 = strategies[i], s2 = strategies[j]; const history1 = [], history2 = []; let score1 = 0, score2 = 0; for (let r = 0; r < rounds; r++) { const move1 = s1.play(history1, history2); const move2 = s2.play(history2, history1); if (move1 && move2) { score1 += R; score2 += R; } else if (move1 && !move2) { score1 += S; score2 += T; } else if (!move1 && move2) { score1 += T; score2 += S; } else { score1 += P; score2 += P; } history1.push(move1); history2.push(move2); } if (i !== j) { scores[s1.name] += score1 / iterations; scores[s2.name] += score2 / iterations; } else scores[s1.name] += score1 / iterations; } } } return Object.entries(scores).sort((a, b) => b[1] - a[1]).map(([name, score]) => ({ name, score })); }
function crucixGameTheory(latest) { const A = [[3, -1], [5, 0]]; const B = [[3, 5], [-1, 0]]; const pureEq = findNashEquilibria(A, B); const mixedEq = mixedNash2x2(A, B); const vix = latest.fred?.vix || 20; const conflicts = latest.gdelt?.conflictEvents?.length || 0; const sanctions = latest.sanctions?.recentCount || 0; const usConfrontProb = Math.min(1, (sanctions + Math.max(0, vix - 20) / 5) / 10); const chinaConfrontProb = Math.min(1, (conflicts + sanctions) / 15); return { payoffMatrix: { A, B }, pureEquilibria: pureEq, mixedEquilibrium: mixedEq, currentState: { usConfrontProbability: usConfrontProb, chinaConfrontProbability: chinaConfrontProb, likelyOutcome: usConfrontProb > 0.5 && chinaConfrontProb > 0.5 ? 'mutual_confront' : usConfrontProb > 0.5 ? 'us_advantage' : chinaConfrontProb > 0.5 ? 'china_advantage' : 'cooperation' }, recommendation: mixedEq ? `Стабильное равновесие: США p=${mixedEq.p.toFixed(2)}, Китай q=${mixedEq.q.toFixed(2)}` : 'Равновесие не найдено', interpretation: usConfrontProb > 0.5 && chinaConfrontProb > 0.5 ? 'высокий риск взаимной эскалации' : usConfrontProb > 0.5 || chinaConfrontProb > 0.5 ? 'асимметричная напряжённость' : 'стабильная кооперация' }; }
export { findNashEquilibria, mixedNash2x2, evolutionarilyStableStrategy, prisonersDilemmaTournament, crucixGameTheory };
