// apis/predict/exotic/infogeo.mjs
// Information Geometry: KL, Fisher, Renyi divergences

function klDivergence(P, Q) { if (P.length !== Q.length) throw new Error('Размеры не совпадают'); let kl = 0; for (let i = 0; i < P.length; i++) if (P[i] > 0) kl += P[i] * Math.log(P[i] / Math.max(Q[i], 1e-15)); return kl; }
function jsDivergence(P, Q) { const M = P.map((p, i) => 0.5 * (p + Q[i])); return 0.5 * klDivergence(P, M) + 0.5 * klDivergence(Q, M); }
function renyiDivergence(P, Q, alpha = 2) { if (alpha === 1) return klDivergence(P, Q); let sum = 0; for (let i = 0; i < P.length; i++) sum += Math.pow(P[i], alpha) * Math.pow(Math.max(Q[i], 1e-15), 1 - alpha); return Math.log(sum) / (alpha - 1); }
function hellingerDistance(P, Q) { let sum = 0; for (let i = 0; i < P.length; i++) sum += (Math.sqrt(P[i]) - Math.sqrt(Q[i])) ** 2; return Math.sqrt(0.5 * sum); }
function fisherNormal(sigma) { return { mu: 1 / (sigma * sigma), sigma: 2 / (sigma * sigma) }; }
function cramerRaoBound(fisherInfo) { return 1 / fisherInfo; }
function mutualInformation(jointCounts, n) { const margX = {}, margY = {}; for (const [key, count] of jointCounts) { const [i, j] = key.split(',').map(Number); margX[i] = (margX[i] || 0) + count; margY[j] = (margY[j] || 0) + count; } let mi = 0; for (const [key, count] of jointCounts) { const [i, j] = key.split(',').map(Number); const pxy = count / n; const px = margX[i] / n; const py = margY[j] / n; mi += pxy * Math.log(pxy / (px * py)); } return mi; }
function entropy(P) { let h = 0; for (const p of P) if (p > 0) h -= p * Math.log2(p); return h; }
function conditionalEntropy(jointCounts, n) { const margY = {}; for (const [key, count] of jointCounts) { const [, j] = key.split(',').map(Number); margY[j] = (margY[j] || 0) + count; } let h = 0; for (const [key, count] of jointCounts) { const [, j] = key.split(',').map(Number); const pxy = count / n; const py = margY[j] / n; h -= pxy * Math.log2(pxy / py); } return h; }
function histogram(arr, bins) { const min = Math.min(...arr); const max = Math.max(...arr); const width = (max - min) / bins || 1; const counts = new Array(bins).fill(0); for (const v of arr) { const idx = Math.min(bins - 1, Math.floor((v - min) / width)); counts[idx]++; } return { edges: Array.from({ length: bins + 1 }, (_, i) => min + i * width), counts }; }
function crucixInfoGeo(history) { const vix = history.map(h => h.fred?.vix).filter(v => v !== undefined && !isNaN(v)); if (vix.length < 40) return { error: 'Мало данных' }; const bins = 15; const half = Math.floor(vix.length / 2); const minV = Math.min(...vix); const maxV = Math.max(...vix); const width = (maxV - minV) / bins; const P = new Array(bins).fill(0); const Q = new Array(bins).fill(0); for (const v of vix.slice(0, half)) P[Math.min(bins - 1, Math.floor((v - minV) / width))]++; for (const v of vix.slice(half)) Q[Math.min(bins - 1, Math.floor((v - minV) / width))]++; const sumP = P.reduce((a, b) => a + b, 0); const sumQ = Q.reduce((a, b) => a + b, 0); const Pnorm = P.map(p => (p + 1e-10) / (sumP + bins * 1e-10)); const Qnorm = Q.map(q => (q + 1e-10) / (sumQ + bins * 1e-10)); return { kl: klDivergence(Pnorm, Qnorm), klReverse: klDivergence(Qnorm, Pnorm), js: jsDivergence(Pnorm, Qnorm), hellinger: hellingerDistance(Pnorm, Qnorm), renyi2: renyiDivergence(Pnorm, Qnorm, 2), entropyOlder: entropy(Pnorm), entropyRecent: entropy(Qnorm), distributionShift: jsDivergence(Pnorm, Qnorm) > 0.1 ? 'significant' : jsDivergence(Pnorm, Qnorm) > 0.03 ? 'moderate' : 'minimal' }; }
export { klDivergence, jsDivergence, renyiDivergence, hellingerDistance, fisherNormal, cramerRaoBound, mutualInformation, entropy, conditionalEntropy, crucixInfoGeo, histogram };
