// apis/predict/exotic/signal_advanced.mjs
// Advanced Signal Processing: Hilbert, EMD, PLV

function hilbertTransform(signal) { const n = signal.length; const real = new Array(n); const imag = new Array(n); for (let t = 0; t < n; t++) { real[t] = signal[t]; imag[t] = 0; for (let s = 0; s < n; s++) { if (s === t) continue; const dt = t - s; imag[t] += signal[s] / (Math.PI * dt); } } const amplitude = real.map((r, i) => Math.sqrt(r * r + imag[i] * imag[i])); const phase = real.map((r, i) => Math.atan2(imag[i], r)); const instFreq = []; for (let i = 1; i < n; i++) { let dphi = phase[i] - phase[i - 1]; while (dphi > Math.PI) dphi -= 2 * Math.PI; while (dphi < -Math.PI) dphi += 2 * Math.PI; instFreq.push(dphi); } return { real, imag, amplitude, phase, instFreq }; }
function findLocalExtrema(signal) { const max = [], min = []; for (let i = 1; i < signal.length - 1; i++) { if (signal[i] > signal[i - 1] && signal[i] > signal[i + 1]) max.push({ i, v: signal[i] }); if (signal[i] < signal[i - 1] && signal[i] < signal[i + 1]) min.push({ i, v: signal[i] }); } return { max, min }; }
function interpolateSpline(xs, ys, length) { const result = new Array(length).fill(0); if (xs.length === 0) return result; for (let i = 0; i < length; i++) { let lo = -1, hi = -1; for (let k = 0; k < xs.length; k++) { if (xs[k] <= i) lo = k; if (xs[k] >= i && hi === -1) hi = k; } if (lo === -1) result[i] = ys[0]; else if (hi === -1) result[i] = ys[ys.length - 1]; else if (lo === hi) result[i] = ys[lo]; else { const t = (i - xs[lo]) / (xs[hi] - xs[lo]); result[i] = ys[lo] + t * (ys[hi] - ys[lo]); } } return result; }
function emd(signal, maxIMFs = 5) { let residual = [...signal]; const imfs = []; for (let k = 0; k < maxIMFs; k++) { const extremes = findLocalExtrema(residual); if (extremes.max.length < 2 || extremes.min.length < 2) break; let imf = [...residual]; for (let s = 0; s < 10; s++) { const { max, min } = findLocalExtrema(imf); if (max.length < 2 || min.length < 2) break; const upper = interpolateSpline(max.map(e => e.i), max.map(e => e.v), imf.length); const lower = interpolateSpline(min.map(e => e.i), min.map(e => e.v), imf.length); const mean = upper.map((u, i) => (u + lower[i]) / 2); imf = imf.map((v, i) => v - mean[i]); } imfs.push(imf); residual = residual.map((v, i) => v - imf[i]); } return { imfs, residual }; }
function phaseLockingValue(signal1, signal2) { const n = Math.min(signal1.length, signal2.length); if (n < 10) return 0; const h1 = hilbertTransform(signal1.slice(0, n)); const h2 = hilbertTransform(signal2.slice(0, n)); let sumCos = 0, sumSin = 0; for (let i = 0; i < n; i++) { const dphi = h1.phase[i] - h2.phase[i]; sumCos += Math.cos(dphi); sumSin += Math.sin(dphi); } return Math.sqrt(sumCos * sumCos + sumSin * sumSin) / n; }
function crucixSignalAdvanced(history) { const vix = history.map(h => h.fred?.vix).filter(v => v !== undefined && !isNaN(v)); const hySpread = history.map(h => h.fred?.hySpread).filter(v => v !== undefined && !isNaN(v)); if (vix.length < 30) return { error: 'Мало данных' }; const vixHilbert = hilbertTransform(vix); const vixEMD = emd(vix, 3); const plv = vix.length === hySpread.length ? phaseLockingValue(vix, hySpread) : 0; const recentFreq = vixHilbert.instFreq.slice(-10); const avgFreq = recentFreq.reduce((a, b) => a + b, 0) / recentFreq.length; const period = Math.abs(avgFreq) > 1e-6 ? 2 * Math.PI / Math.abs(avgFreq) : Infinity; return { hilbert: { currentAmplitude: vixHilbert.amplitude[vixHilbert.amplitude.length - 1], currentPhase: vixHilbert.phase[vixHilbert.phase.length - 1], avgFrequency: avgFreq, estimatedPeriod: period }, emd: { nIMFs: vixEMD.imfs.length, imfEnergies: vixEMD.imfs.map(imf => imf.reduce((s, v) => s + v * v, 0) / imf.length), residualEnergy: vixEMD.residual.reduce((s, v) => s + v * v, 0) / vixEMD.residual.length }, phaseLocking: { vixHyPLV: plv, interpretation: plv > 0.7 ? 'высокая синхронизация' : plv > 0.4 ? 'умеренная' : 'слабая' }, interpretation: { cycle: period < 30 ? `короткий цикл ${period.toFixed(1)} шагов` : period < 100 ? `средний цикл ${period.toFixed(1)}` : 'долгосрочный тренд', synchronization: plv > 0.5 ? 'VIX и спред движутся синхронно' : 'сигналы рассинхронизированы' } }; }
export { hilbertTransform, emd, phaseLockingValue, crucixSignalAdvanced };
