// apis/predict/exotic/wasserstein.mjs
// Optimal Transport: Wasserstein distance

function quantileFromSorted(sorted, p) { if (sorted.length === 0) return 0; const idx = p * (sorted.length - 1); const lo = Math.floor(idx), hi = Math.ceil(idx); if (lo === hi) return sorted[lo]; return sorted[lo] + (sorted[hi] - sorted[lo]) * (idx - lo); }
function euclidean(a, b) { let s = 0; for (let i = 0; i < a.length; i++) s += (a[i] - b[i]) ** 2; return Math.sqrt(s); }
function wasserstein1D(samplesP, samplesQ, p = 1) { const sortedP = [...samplesP].sort((a, b) => a - b); const sortedQ = [...samplesQ].sort((a, b) => a - b); const n = Math.min(sortedP.length, sortedQ.length); const quantilesP = [], quantilesQ = []; for (let i = 0; i < n; i++) { quantilesP.push(quantileFromSorted(sortedP, i / (n - 1))); quantilesQ.push(quantileFromSorted(sortedQ, i / (n - 1))); } let sum = 0; for (let i = 0; i < n; i++) sum += Math.pow(Math.abs(quantilesP[i] - quantilesQ[i]), p); return Math.pow(sum / n, 1 / p); }
function wassersteinND(pointsP, pointsQ, p = 2, reg = 0.1, iterations = 100) { const n = pointsP.length; const m = pointsQ.length; const C = Array.from({ length: n }, (_, i) => Array.from({ length: m }, (_, j) => Math.pow(euclidean(pointsP[i], pointsQ[j]), p))); const K = C.map(row => row.map(c => Math.exp(-c / reg))); const a = new Array(n).fill(1 / n); const b = new Array(m).fill(1 / m); const u = new Array(n).fill(1); const v = new Array(m).fill(1); for (let iter = 0; iter < iterations; iter++) { for (let i = 0; i < n; i++) { let sum = 0; for (let j = 0; j < m; j++) sum += K[i][j] * v[j]; u[i] = a[i] / (sum || 1e-15); } for (let j = 0; j < m; j++) { let sum = 0; for (let i = 0; i < n; i++) sum += K[i][j] * u[i]; v[j] = b[j] / (sum || 1e-15); } } let dist = 0; for (let i = 0; i < n; i++) for (let j = 0; j < m; j++) dist += u[i] * K[i][j] * v[j] * C[i][j]; return Math.pow(dist, 1 / p); }
function wassersteinBarycenter(distributions, weights = null, iterations = 50) { const n = distributions.length; const w = weights || new Array(n).fill(1 / n); const m = distributions[0].length; let barycenter = [...distributions[0]]; for (let iter = 0; iter < iterations; iter++) { const sortedDists = distributions.map(d => [...d].sort((a, b) => a - b)); const newBarycenter = []; for (let i = 0; i < m; i++) { let sum = 0; for (let k = 0; k < n; k++) sum += w[k] * sortedDists[k][i]; newBarycenter.push(sum); } barycenter = newBarycenter; } return barycenter; }
function histogram(arr, bins) { const min = Math.min(...arr); const max = Math.max(...arr); const width = (max - min) / bins || 1; const counts = new Array(bins).fill(0); for (const v of arr) { const idx = Math.min(bins - 1, Math.floor((v - min) / width)); counts[idx]++; } return { edges: Array.from({ length: bins + 1 }, (_, i) => min + i * width), counts }; }
function crucixWasserstein(history) { const vix = history.map(h => h.fred?.vix).filter(v => v !== undefined && !isNaN(v)); if (vix.length < 30) return { error: 'Мало данных' }; const half = Math.floor(vix.length / 2); const recent = vix.slice(half); const older = vix.slice(0, half); const w1 = wasserstein1D(older, recent, 1); const w2 = wasserstein1D(older, recent, 2); const mean = vix.reduce((a, b) => a + b, 0) / vix.length; const std = Math.sqrt(vix.reduce((s, v) => s + (v - mean) ** 2, 0) / vix.length) || 1; const normalizedW1 = w1 / std; return { wasserstein1: w1, wasserstein2: w2, normalizedW1, recentMean: recent.reduce((a, b) => a + b, 0) / recent.length, olderMean: older.reduce((a, b) => a + b, 0) / older.length, drift: normalizedW1 > 0.5 ? 'significant' : normalizedW1 > 0.2 ? 'moderate' : 'stable', interpretation: normalizedW1 > 0.5 ? 'распределение VIX существенно сдвинулось' : normalizedW1 > 0.2 ? 'умеренный сдвиг' : 'распределение стабильно' }; }
export { wasserstein1D, wassersteinND, wassersteinBarycenter, crucixWasserstein, quantileFromSorted, euclidean };
