// apis/predict/core/linear_algebra.mjs
// Математическое ядро: линейная алгебра на чистом JS

function zeros(n, m) { const r = []; for (let i = 0; i < n; i++) r.push(new Float64Array(m)); return r; }
function identity(n) { const M = zeros(n, n); for (let i = 0; i < n; i++) M[i][i] = 1; return M; }
function clone(A) { return A.map(row => new Float64Array(row)); }
function matmul(A, B) { const n = A.length, k = A[0].length, m = B[0].length; const C = zeros(n, m); for (let i = 0; i < n; i++) { for (let l = 0; l < k; l++) { const a = A[i][l]; if (a === 0) continue; const Bl = B[l]; for (let j = 0; j < m; j++) C[i][j] += a * Bl[j]; } } return C; }
function transpose(A) { const n = A.length, m = A[0].length; const T = zeros(m, n); for (let i = 0; i < n; i++) for (let j = 0; j < m; j++) T[j][i] = A[i][j]; return T; }
function lu(A) { const n = A.length; const LU = clone(A); const P = Array(n).fill(0).map((_, i) => i); let sign = 1; for (let k = 0; k < n - 1; k++) { let maxVal = Math.abs(LU[k][k]); let maxIdx = k; for (let i = k + 1; i < n; i++) { if (Math.abs(LU[i][k]) > maxVal) { maxVal = Math.abs(LU[i][k]); maxIdx = i; } } if (maxIdx !== k) { [LU[k], LU[maxIdx]] = [LU[maxIdx], LU[k]]; [P[k], P[maxIdx]] = [P[maxIdx], P[k]]; sign = -sign; } if (Math.abs(LU[k][k]) < 1e-14) continue; for (let i = k + 1; i < n; i++) { LU[i][k] /= LU[k][k]; for (let j = k + 1; j < n; j++) LU[i][j] -= LU[i][k] * LU[k][j]; } } return { LU, P, sign }; }
function solve(A, b) { const n = A.length; const { LU, P } = lu(A); const x = new Float64Array(n); const bPerm = new Float64Array(n); for (let i = 0; i < n; i++) bPerm[i] = b[P[i]]; const y = new Float64Array(n); for (let i = 0; i < n; i++) { let sum = bPerm[i]; for (let j = 0; j < i; j++) sum -= LU[i][j] * y[j]; y[i] = sum; } for (let i = n - 1; i >= 0; i--) { let sum = y[i]; for (let j = i + 1; j < n; j++) sum -= LU[i][j] * x[j]; x[i] = sum / LU[i][i]; } return x; }
function inverse(A) { const n = A.length; const { LU, P } = lu(A); const result = zeros(n, n); for (let col = 0; col < n; col++) { const b = new Float64Array(n); b[P[col]] = 1; const y = new Float64Array(n); for (let i = 0; i < n; i++) { let sum = b[i]; for (let j = 0; j < i; j++) sum -= LU[i][j] * y[j]; y[i] = sum; } const x = new Float64Array(n); for (let i = n - 1; i >= 0; i--) { let sum = y[i]; for (let j = i + 1; j < n; j++) sum -= LU[i][j] * x[j]; x[i] = sum / LU[i][i]; } for (let i = 0; i < n; i++) result[i][col] = x[i]; } return result; }
function det(A) { const { LU, sign } = lu(A); let d = sign; for (let i = 0; i < LU.length; i++) d *= LU[i][i]; return d; }
function cholesky(A) { const n = A.length; const L = zeros(n, n); for (let i = 0; i < n; i++) { for (let j = 0; j <= i; j++) { let sum = 0; for (let k = 0; k < j; k++) sum += L[i][k] * L[j][k]; if (i === j) { L[i][j] = Math.sqrt(Math.max(A[i][i] - sum, 1e-14)); } else { L[i][j] = (A[i][j] - sum) / (L[j][j] || 1e-14); } } } return L; }
function qr(A) { const n = A.length, m = A[0].length; const R = clone(A); const Q = identity(n); const minNM = Math.min(n - 1, m); for (let k = 0; k < minNM; k++) { let norm = 0; for (let i = k; i < n; i++) norm += R[i][k] ** 2; norm = Math.sqrt(norm); if (norm < 1e-14) continue; const alpha = R[k][k] > 0 ? -norm : norm; const v = new Float64Array(n); v[k] = R[k][k] - alpha; for (let i = k + 1; i < n; i++) v[i] = R[i][k]; let vNorm2 = 0; for (let i = k; i < n; i++) vNorm2 += v[i] ** 2; if (vNorm2 < 1e-14) continue; for (let j = k; j < m; j++) { let dot = 0; for (let i = k; i < n; i++) dot += v[i] * R[i][j]; const factor = 2 * dot / vNorm2; for (let i = k; i < n; i++) R[i][j] -= factor * v[i]; } for (let j = 0; j < n; j++) { let dot = 0; for (let i = k; i < n; i++) dot += v[i] * Q[j][i]; const factor = 2 * dot / vNorm2; for (let i = k; i < n; i++) Q[j][i] -= factor * v[i]; } } return { Q: transpose(Q), R }; }
function jacobiEigen(A, maxIter = 100, tol = 1e-9) { const n = A.length; const M = clone(A); const V = identity(n); for (let iter = 0; iter < maxIter; iter++) { let maxOff = 0, p = 0, q = 1; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) if (Math.abs(M[i][j]) > maxOff) { maxOff = Math.abs(M[i][j]); p = i; q = j; } if (maxOff < tol) break; const app = M[p][p], aqq = M[q][q], apq = M[p][q]; const theta = 0.5 * Math.atan2(2 * apq, app - aqq); const c = Math.cos(theta), s = Math.sin(theta); for (let i = 0; i < n; i++) { const mip = M[i][p], miq = M[i][q]; M[i][p] = c * mip - s * miq; M[i][q] = s * mip + c * miq; } for (let j = 0; j < n; j++) { const mpj = M[p][j], mqj = M[q][j]; M[p][j] = c * mpj - s * mqj; M[q][j] = s * mpj + c * mqj; } for (let i = 0; i < n; i++) { const vip = V[i][p], viq = V[i][q]; V[i][p] = c * vip - s * viq; V[i][q] = s * vip + c * viq; } } const eigenvalues = M.map((row, i) => row[i]); const idx = eigenvalues.map((v, i) => ({ v, i })).sort((a, b) => b.v - a.v); const sortedValues = idx.map(x => x.v); const sortedVectors = idx.map(x => V.map(row => row[x.i])); const Vt = zeros(n, n); for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) Vt[i][j] = sortedVectors[j][i]; return { eigenvalues: sortedValues, eigenvectors: Vt }; }
function svd(A, maxIter = 100, tol = 1e-9) { const n = A.length, m = A[0].length; const AtA = matmul(transpose(A), A); const { eigenvalues, eigenvectors } = jacobiEigen(AtA, maxIter, tol); const singularValues = eigenvalues.map(v => Math.sqrt(Math.max(v, 0))); const V = eigenvectors; const AV = matmul(A, V); const U = zeros(n, m); for (let i = 0; i < n; i++) for (let j = 0; j < m; j++) { const s = singularValues[j]; U[i][j] = s > 1e-10 ? AV[i][j] / s : 0; } return { U, S: singularValues, V }; }
function pinv(A, tol = 1e-10) { const { U, S, V } = svd(A); const n = A.length, m = A[0].length; const Smax = Math.max(...S); const cutoff = tol * Smax; const SInv = zeros(m, n); for (let i = 0; i < S.length; i++) if (S[i] > cutoff) SInv[i][i] = 1 / S[i]; return matmul(matmul(V, SInv), transpose(U)); }
function lstsq(A, b) { const AtA = matmul(transpose(A), A); const Atb = matmul(transpose(A), b.map(x => [x])).map(row => row[0]); return solve(AtA, Atb); }
function conditionNumber(A) { const { S } = svd(A); const maxS = Math.max(...S); const minS = Math.min(...S.filter(s => s > 1e-14)); return maxS / minS; }
export { zeros, identity, clone, matmul, transpose, lu, solve, inverse, det, cholesky, qr, svd, jacobiEigen, pinv, lstsq, conditionNumber };
