// apis/predict/core/stats.mjs
// Статистические распределения и функции на чистом JS

function logGamma(z) { if (z < 0.5) return Math.log(Math.PI / Math.sin(Math.PI * z)) - logGamma(1 - z); z -= 1; const g = 7; const c = [0.99999999999980993, 676.5203681218851, -1259.1392167224028, 771.32342877765313, -176.61502916214059, 12.507343278686905, -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7]; let x = c[0]; for (let i = 1; i < g + 2; i++) x += c[i] / (z + i); const t = z + g + 0.5; return 0.5 * Math.log(2 * Math.PI) + (z + 0.5) * Math.log(t) - t + Math.log(x); }
function gamma(z) { return Math.exp(logGamma(z)); }
function beta(a, b) { return Math.exp(logGamma(a) + logGamma(b) - logGamma(a + b)); }
function logBeta(a, b) { return logGamma(a) + logGamma(b) - logGamma(a + b); }
function gammaP(s, x) { if (x <= 0) return 0; if (x < s + 1) { let sum = 1 / s; let term = sum; for (let n = 1; n < 200; n++) { term *= x / (s + n); sum += term; if (Math.abs(term) < 1e-14 * Math.abs(sum)) break; } return sum * Math.exp(-x + s * Math.log(x) - logGamma(s)); } return 1 - gammaQ(s, x); }
function gammaQ(s, x) { const tiny = 1e-30; let b = x + 1 - s; let c = 1 / tiny; let d = 1 / b; let h = d; for (let i = 1; i < 200; i++) { const an = -i * (i - s); b += 2; d = an * d + b; if (Math.abs(d) < tiny) d = tiny; c = b + an / c; if (Math.abs(c) < tiny) c = tiny; d = 1 / d; const del = d * c; h *= del; if (Math.abs(del - 1) < 1e-14) break; } return Math.exp(-x + s * Math.log(x) - logGamma(s)) * h; }
function incompleteBeta(x, a, b) { if (x <= 0) return 0; if (x >= 1) return 1; const bt = Math.exp(logGamma(a + b) - logGamma(a) - logGamma(b) + a * Math.log(x) + b * Math.log(1 - x)); if (x < (a + 1) / (a + b + 2)) return bt * betaCF(x, a, b) / a; return 1 - bt * betaCF(1 - x, b, a) / b; }
function betaCF(x, a, b) { const maxIter = 200, eps = 1e-14; const qab = a + b, qap = a + 1, qam = a - 1; let c = 1; let d = 1 - qab * x / qap; if (Math.abs(d) < 1e-30) d = 1e-30; d = 1 / d; let h = d; for (let m = 1; m <= maxIter; m++) { const m2 = 2 * m; let aa = m * (b - m) * x / ((qam + m2) * (a + m2)); d = 1 + aa * d; if (Math.abs(d) < 1e-30) d = 1e-30; c = 1 + aa / c; if (Math.abs(c) < 1e-30) c = 1e-30; d = 1 / d; h *= d * c; aa = -(a + m) * (qab + m) * x / ((a + m2) * (qap + m2)); d = 1 + aa * d; if (Math.abs(d) < 1e-30) d = 1e-30; c = 1 + aa / c; if (Math.abs(c) < 1e-30) c = 1e-30; d = 1 / d; const del = d * c; h *= del; if (Math.abs(del - 1) < eps) break; } return h; }
function erf(x) { const sign = x < 0 ? -1 : 1; x = Math.abs(x); const t = 1 / (1 + 0.3275911 * x); const y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x); return sign * y; }
function erfc(x) { return 1 - erf(x); }
function erfInv(x) { if (x === 0) return 0; const a = [0, 0.886226899, -1.645349621, 0.914624893, -0.140543331]; const b = [1, -2.118377725, 1.442710462, -0.329097515, 0.012229801]; const c = [-1.970840454, -1.624906493, 3.429567803, 1.641345311]; const d = [1, 3.543889200, 1.637067800]; const sign = x < 0 ? -1 : 1; x = Math.abs(x); let result; if (x <= 0.7) { const x2 = x * x; result = x * (((a[4] * x2 + a[3]) * x2 + a[2]) * x2 + a[1]) / ((((b[4] * x2 + b[3]) * x2 + b[2]) * x2 + b[1]) * x2 + b[0]); } else if (x < 1) { const y = Math.sqrt(-Math.log((1 - x) / 2)); result = (((c[3] * y + c[2]) * y + c[1]) * y + c[0]) / ((d[2] * y + d[1]) * y + d[0]); } else return sign * Infinity; for (let i = 0; i < 2; i++) result = result - (erf(result) - sign * x) / (2 / Math.sqrt(Math.PI) * Math.exp(-result * result)); return sign * result; }
function normalCDF(x, mu = 0, sigma = 1) { return 0.5 * (1 + erf((x - mu) / (sigma * Math.SQRT2))); }
function normalPDF(x, mu = 0, sigma = 1) { const z = (x - mu) / sigma; return Math.exp(-0.5 * z * z) / (sigma * Math.sqrt(2 * Math.PI)); }
function normalQuantile(p, mu = 0, sigma = 1) { return mu + sigma * Math.SQRT2 * erfInv(2 * p - 1); }
function studentTCDF(t, df) { const x = df / (df + t * t); const p = 0.5 * incompleteBeta(x, df / 2, 0.5); return t > 0 ? 1 - p : p; }
function studentTPDF(t, df) { return Math.exp(logGamma((df + 1) / 2) - logGamma(df / 2)) / Math.sqrt(df * Math.PI) * Math.pow(1 + t * t / df, -(df + 1) / 2); }
function chiSquareCDF(x, k) { return gammaP(k / 2, x / 2); }
function chiSquareQuantile(p, k) { let x = k; for (let i = 0; i < 20; i++) { const cdf = chiSquareCDF(x, k); const pdf = Math.exp((k / 2 - 1) * Math.log(x / 2) - x / 2 - logGamma(k / 2)) / 2; if (pdf < 1e-15) break; const delta = (cdf - p) / pdf; x = Math.max(0.001, x - delta); if (Math.abs(delta) < 1e-8) break; } return x; }
function fCDF(x, d1, d2) { return incompleteBeta(d1 * x / (d1 * x + d2), d1 / 2, d2 / 2); }
function gammaCDF(x, shape, scale = 1) { return gammaP(shape, x / scale); }
function gammaQuantile(p, shape, scale = 1) { let x = shape * scale; for (let i = 0; i < 30; i++) { const cdf = gammaCDF(x, shape, scale); const pdf = Math.exp((shape - 1) * Math.log(x) - x / scale - logGamma(shape) - shape * Math.log(scale)); if (pdf < 1e-15) break; const delta = (cdf - p) / pdf; x = Math.max(0.001, x - delta); if (Math.abs(delta / x) < 1e-8) break; } return x; }
function betaCDF(x, a, b) { return incompleteBeta(x, a, b); }
function betaQuantile(p, a, b) { let x = a / (a + b); for (let i = 0; i < 30; i++) { const cdf = betaCDF(x, a, b); const pdf = Math.exp((a - 1) * Math.log(x) + (b - 1) * Math.log(1 - x) - logBeta(a, b)); if (pdf < 1e-15) break; const delta = (cdf - p) / pdf; x = Math.max(0.001, Math.min(0.999, x - delta)); if (Math.abs(delta) < 1e-8) break; } return x; }
function mean(arr) { if (arr.length === 0) return 0; return arr.reduce((a, b) => a + b, 0) / arr.length; }
function variance(arr, ddof = 1) { const n = arr.length; if (n <= ddof) return 0; const m = mean(arr); return arr.reduce((s, v) => s + (v - m) ** 2, 0) / (n - ddof); }
function std(arr, ddof = 1) { return Math.sqrt(variance(arr, ddof)); }
function median(arr) { if (arr.length === 0) return 0; const sorted = [...arr].sort((a, b) => a - b); const n = sorted.length; return n % 2 === 0 ? (sorted[n / 2 - 1] + sorted[n / 2]) / 2 : sorted[(n - 1) / 2]; }
function quantile(arr, p) { if (arr.length === 0) return 0; const sorted = [...arr].sort((a, b) => a - b); const idx = p * (sorted.length - 1); const lo = Math.floor(idx), hi = Math.ceil(idx); if (lo === hi) return sorted[lo]; return sorted[lo] + (sorted[hi] - sorted[lo]) * (idx - lo); }
function skewness(arr) { const n = arr.length; if (n < 3) return 0; const m = mean(arr), s = std(arr); return (n / ((n - 1) * (n - 2))) * arr.reduce((sum, v) => sum + ((v - m) / s) ** 3, 0); }
function kurtosis(arr) { const n = arr.length; if (n < 4) return 0; const m = mean(arr), s = std(arr); const sum = arr.reduce((acc, v) => acc + ((v - m) / s) ** 4, 0); return (n * (n + 1) / ((n - 1) * (n - 2) * (n - 3))) * sum - 3 * (n - 1) ** 2 / ((n - 2) * (n - 3)); }
function covariance(x, y, ddof = 1) { const n = x.length; if (n <= ddof) return 0; const mx = mean(x), my = mean(y); return x.reduce((s, xi, i) => s + (xi - mx) * (y[i] - my), 0) / (n - ddof); }
function correlation(x, y) { const sx = std(x), sy = std(y); if (sx === 0 || sy === 0) return 0; return covariance(x, y) / (sx * sy); }
function spearman(x, y) { const rank = (arr) => { const sorted = arr.map((v, i) => ({ v, i })).sort((a, b) => a.v - b.v); const ranks = new Array(arr.length); sorted.forEach((item, idx) => { ranks[item.i] = idx + 1; }); return ranks; }; return correlation(rank(x), rank(y)); }
function kendallTau(x, y) { const n = x.length; let c = 0, d = 0; for (let i = 0; i < n - 1; i++) { for (let j = i + 1; j < n; j++) { const dx = x[i] - x[j], dy = y[i] - y[j]; if (dx * dy > 0) c++; else if (dx * dy < 0) d++; } } return (c - d) / (0.5 * n * (n - 1)); }
function histogram(arr, bins = 20) { if (arr.length === 0) return { edges: [], counts: [] }; const min = Math.min(...arr), max = Math.max(...arr); const width = (max - min) / bins || 1; const edges = []; const counts = new Array(bins).fill(0); for (let i = 0; i <= bins; i++) edges.push(min + i * width); for (const v of arr) { const idx = Math.min(bins - 1, Math.floor((v - min) / width)); counts[idx]++; } return { edges, counts, width }; }
function kde(arr, bandwidth = null, points = 100) { const n = arr.length; if (n === 0) return { x: [], y: [] }; if (bandwidth === null) { const s = std(arr); const iqr = quantile(arr, 0.75) - quantile(arr, 0.25); bandwidth = 0.9 * Math.min(s, iqr / 1.34) * Math.pow(n, -0.2); if (bandwidth === 0) bandwidth = 1; } const min = Math.min(...arr) - 3 * bandwidth; const max = Math.max(...arr) + 3 * bandwidth; const step = (max - min) / (points - 1); const x = [], y = []; for (let i = 0; i < points; i++) { const xi = min + i * step; let yi = 0; for (const v of arr) { const z = (xi - v) / bandwidth; yi += Math.exp(-0.5 * z * z) / Math.sqrt(2 * Math.PI); } x.push(xi); y.push(yi / (n * bandwidth)); } return { x, y, bandwidth }; }
function tTestOneSample(arr, mu0 = 0) { const n = arr.length; const m = mean(arr), s = std(arr); const t = (m - mu0) / (s / Math.sqrt(n)); const p = 2 * (1 - studentTCDF(Math.abs(t), n - 1)); return { t, df: n - 1, pValue: p, mean: m, std: s }; }
function tTestTwoSample(x, y) { const nx = x.length, ny = y.length; const mx = mean(x), my = mean(y); const sx = variance(x), sy = variance(y); const pooledVar = ((nx - 1) * sx + (ny - 1) * sy) / (nx + ny - 2); const t = (mx - my) / Math.sqrt(pooledVar * (1 / nx + 1 / ny)); const df = nx + ny - 2; const p = 2 * (1 - studentTCDF(Math.abs(t), df)); return { t, df, pValue: p, meanDiff: mx - my }; }
function chiSquareTest(observed, expected) { let chi2 = 0; for (let i = 0; i < observed.length; i++) chi2 += (observed[i] - expected[i]) ** 2 / (expected[i] || 1); const df = observed.length - 1; const p = 1 - chiSquareCDF(chi2, df); return { chi2, df, pValue: p }; }
function aic(logLikelihood, nParams) { return -2 * logLikelihood + 2 * nParams; }
function bic(logLikelihood, nParams, n) { return -2 * logLikelihood + nParams * Math.log(n); }
export { logGamma, gamma, beta, logBeta, gammaP, gammaQ, incompleteBeta, erf, erfc, erfInv, normalCDF, normalPDF, normalQuantile, studentTCDF, studentTPDF, chiSquareCDF, chiSquareQuantile, fCDF, gammaCDF, gammaQuantile, betaCDF, betaQuantile, mean, variance, std, median, quantile, skewness, kurtosis, covariance, correlation, spearman, kendallTau, histogram, kde, tTestOneSample, tTestTwoSample, chiSquareTest, aic, bic };
